### ISSUE TITLE
怎么导入工程中android-pluginmgr的代码

### ISSUE THREAD

**Issue by kissazi2** [houkx/android-pluginmgr#11]
同标题。无法通过Eclipse用Android项目的方式导入。您是怎么导入的呢？

**Comment by houkx** [comment]
Maven Project, not Android Project.

2015-04-03 7:08 GMT+08:00 kissazi2 <notifications@github.com>:

**Comment by houkx** [comment]
Import->General->existing projects into Workspace, if your eclipse support
maven.

2015-04-03 15:15 GMT+08:00 Kangxi Hou <hkx.aidream@gmail.com>:

**Comment by houkx** [comment]
這也提個bug...
