### ISSUE TITLE
【求助】  各位大神们，谁能告诉我，我为什么没法把库导入到eclipse中？

### ISSUE THREAD

**Issue by max8888888** [houkx/android-pluginmgr#21]
大神们好，我想研究一下插件开发，发现了这个框架，更发现是国人开发的。
但我导入的时候遇到了点小麻烦。

正常导入library工程，会报错，出现两个src文件夹。其中一个是main.iml。IDE总将这个工程认作JAVA工程。手动创建了个android工程，在把这个工程覆盖进去也不行。

是不是通常的导入方法不行么？哪个用这个的大神能跟我说下，这种工程的导入方法么？

**Comment by max8888888** [comment]
我导入的方法就是右键，Import，然后选android下的"Existiong Android Code Into Workspace"，然后选工程。  这种导入方式是不是不对？

**Comment by MMLoveMeMM** [comment]
hi,遇到具体什么问题,可以和我沟通一起看看

**Comment by max8888888** [comment]
您好，我遇到的问题是，这个框架使用的第一步，将它导入到eclipse中。这部会遇到个错误，就是导入的工程报错，调了半天，不知道怎么办好了。

**Comment by max8888888** [comment]
您能说下，您是怎么导入那个android-pluginmgr库的么？

**Comment by MMLoveMeMM** [comment]
你加我的QQ : 270791800

**Comment by max8888888** [comment]
好，谢谢！
