### ISSUE TITLE
运行插件的启动结果

### ISSUE THREAD

**Issue by ChanKingBooo** [houkx/android-pluginmgr#24]
@houkx 楼主的demo运行没有任何问题。
为什么我copy到我的项目之后打开插件之后的内容就是PluginActivity的内容呢？
例如一个extends Activity的空PluginActivity打开任何插件都是带标题的黑屏~
不知道是我哪里弄的不对~

**Comment by YangJiaYe** [comment]
@asLody

**Comment by YangJiaYe** [comment]
@houkx 这个必须要把v4包删掉吗?
