### ISSUE TITLE
No PluginActivity

### ISSUE THREAD

**Issue by rokasjasonas** [houkx/android-pluginmgr#3]
Missing androidx.pluginmgr.PluginActivity

**Comment by houkx** [comment]
oh, it will be generated at runtime.

**Comment by houkx** [comment]
when you start an plugin activity, it will automatic generate an activity such as:
public class androidx.pluginmgr.PluginActivity extends YourPlugActivity{
 .... 
}, place in /data/data/yourFrameworkPkg/plugId/activities/YourPlugActivity.dex

**Comment by rokasjasonas** [comment]
So I need root permissions?

**Comment by houkx** [comment]
no need, just sdcard rw permissions
