### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by rokasjasonas** [houkx/android-pluginmgr#4]
Error:Execution failed for task ':app:packageAllReleaseClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: android/widget/ViewStub$OnInflateListener.class

can't compile. lib contains same class as Android

**Comment by houkx** [comment]
do you use the PlugLoadDemo ?

**Comment by rokasjasonas** [comment]
I used libs from PlugLoadDemo and code lines from tutorial in main page

**Comment by houkx** [comment]
did you have another jar contains class: android.widget.ViewStub

**Comment by rokasjasonas** [comment]
maybe support or appcompat

**Comment by houkx** [comment]
if so, you can remove the android/widget/ViewStub.class and it's subclass such as android/widget/ViewStub$OnInflateListener.class...

**Comment by houkx** [comment]
experiment brach has fix it
