### ISSUE TITLE
androidx.pluginmgr.PluginActivity not found

### ISSUE THREAD

**Issue by bunnyblue** [houkx/android-pluginmgr#7]
03-11 14:32:12.219: E/AndroidRuntime(11016): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.pluginmgr.PluginActivity" on path: DexPathList[[zip file "/data/app/androidx.plmgrdemo-1.apk"],nativeLibraryDirectories=[/data/app-lib/androidx.plmgrdemo-1, /vendor/lib, /data/cust/lib, /system/lib]]

**Comment by houkx** [comment]
这个不是单独的异常，你前面提的那个才是问题
