### ISSUE TITLE
getEntry failing because entryIndex 79 is beyond type entryCount 5

### ISSUE THREAD

**Issue by bunnyblue** [houkx/android-pluginmgr#8]
03-11 15:07:29.149: V/SlidingMenu(19321): setting padding!
03-11 15:07:29.179: W/ResourceType(19321): getEntry failing because entryIndex 79 is beyond type entryCount 5
03-11 15:07:29.179: W/ResourceType(19321): Failure getting entry for 0x7f04004f (t=3 e=79) in package 0 (error -2147483647)
03-11 15:07:29.189: D/AndroidRuntime(19321): Shutting down VM
03-11 15:07:29.189: W/dalvikvm(19321): threadid=1: thread exiting with uncaught exception (group=0x417c9c50)
03-11 15:07:29.189: E/AndroidRuntime(19321): FATAL EXCEPTION: main
03-11 15:07:29.189: E/AndroidRuntime(19321): Process: androidx.plmgrdemo, PID: 19321
03-11 15:07:29.189: E/AndroidRuntime(19321): android.content.res.Resources$NotFoundException: Resource ID #0x7f04004f
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.content.res.Resources.getValue(Resources.java:1170)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2379)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.content.res.Resources.getLayout(Resources.java:986)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at com.xiaowangcai.xwc.adapter.MenuListAdapter.getView(MenuListAdapter.java:40)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.widget.AbsListView.obtainView(AbsListView.java:2263)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.widget.ListView.makeAndAddView(ListView.java:1790)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.widget.ListView.fillDown(ListView.java:691)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.widget.ListView.fillFromTop(ListView.java:752)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.widget.ListView.layoutChildren(ListView.java:1630)
03-11 15:07:29.189: E/AndroidRuntime(19321): 	at android.widget.AbsListView.onLayout(AbsListView.java:2091)

**Comment by bunnyblue** [comment]
experienceexperiment  分支

**Comment by houkx** [comment]
bug 都可以解决 只是目前没精力搞

**Comment by bunnyblue** [comment]
solved

**Comment by jbfitbit** [comment]
How did you solve it?
