### ISSUE TITLE
出现ClassCastException 不知道怎么回事

### ISSUE THREAD

**Issue by fayou147** [houkx/android-pluginmgr#9]
03-12 10:59:50.200: E/AndroidRuntime(6374): Caused by: java.lang.ClassCastException: androidx.pluginmgr.PluginContextWrapper cannot be cast to android.app.Application

**Comment by houkx** [comment]
使用哪个分支的代码？experiment分支应该没有这个问题吧

**Comment by fayou147** [comment]
dev上的

**Comment by houkx** [comment]
这个来自比较老的版本了 不是我维护的了

**Comment by fayou147** [comment]
用了一下experiment分支 出现ANR了 dev上的有的apk还是能用的    experiment直接不能用  看了 一下好像是PluginPackageManager在getActivityIcon的时候int icon = actInfo.icon;的值=0;所以递归了  但是说递归的话又没有在循环输出log。实在是想不明白

**Comment by fayou147** [comment]
static final String targetClassName = "androidx.pluginmgr.PluginActivity";没这个类啊！！

**Comment by houkx** [comment]
这样吧 你把dev里面PluginContextWrapper  的geApplicationContext（）方法的
return this 改为 return plugin.getApplication()

**Comment by fayou147** [comment]
好像我手机的问题
Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1053 com.android.server.am.OppoActivityStackHelper.sendIsHomeModeIntent:65 com.android.server.am.OppoActivityStackHelper.handleSendHomeMode:92 com.android.server.am.ActivityStack.resumeTopActivityLocked:1526 com.android.server.am.ActivityStack.resumeTopActivityLocked:1492 
我用的一加手机 用的rom就是Oppo的 看样子和Oppo有关
